Обновлены модели Account.GetPrivacySettings и PhotoAlbum.PrivacyView.
vknet/vk pull request #1160
Opened 2021-05-10 13:12 UTC by DeNcHiK3713

## Список изменений
- Исправил баг #1158, связанный сновой версией api:
- Обновил модели
- Обновил тесты

##### Обязательно выполните следующие пункты:
- [x] Проверьте что ваш код не содержит конфликтов, и исправьте их по необходимости
- [x] Напишите тесты, и обязательно проверьте что не падают другие.

##
#### Внимание! Pull Request'ы с непройденными тестами не принимаются

2021-05-11 08:48 UTC, inyutin-maxim requested changes

2021-05-11 08:48 UTC, inyutin-maxim commented on VkNet/Abstractions/Category/Async/IVideoCategoryAsync.cs
> +		Task<long> AddAlbumAsync(string title, long? groupId = null, Privacy privacy = null);
Здесь не просто так было перечисление, у параметра тип `список слов, разделенных через запятую`

2021-05-11 08:48 UTC, inyutin-maxim commented on VkNet/Abstractions/Category/IVideoCategory.cs
> +		long AddAlbum(string title, long? groupId = null, Privacy privacy = null);
Здесь не просто так было перечисление, у параметра тип `список слов, разделенных через запятую`

2021-05-11 08:48 UTC, inyutin-maxim commented on VkNet/Categories/Async/VideoCategoryAsync.cs
> +		public Task<long> AddAlbumAsync(string title, long? groupId = null, Privacy privacy = null)
Здесь не просто так было перечисление, у параметра тип `список слов, разделенных через запятую`

2021-05-11 08:48 UTC, inyutin-maxim commented on VkNet/Model/PhotoAlbum.cs
> +		public Privacy PrivacyView { get; set; }
Здесь не просто так было перечисление, у альбома может быть более одной политики приватности

2021-05-11 08:48 UTC, inyutin-maxim commented on VkNet/Model/PhotoAlbum.cs
> +		public Privacy PrivacyComment { get; set; }
Здесь не просто так было перечисление, у альбома может быть более одной политики приватности

2023-03-16 23:30 UTC, Panuchi commented
Закрыл т.к. PR не был исправлен. Обновил настройки приватности #1442

2023-03-16 23:30 UTC, closed without merging