Исправление ошибки при превышении MaxDepth при парсинге обновлений от вк
vknet/vk pull request #1212
Opened 2021-11-07 01:40 UTC by xeleoss

## Список изменений
- Изменение 1

##### Обязательно выполните следующие пункты:
- [ ] Проверьте что ваш код не содержит конфликтов, и исправьте их по необходимости
- [ ] Напишите тесты, и обязательно проверьте что не падают другие.

##### Внимание! Pull Request'ы с непройденными тестами не принимаются

2021-11-07 20:34 UTC, xeleoss commented
С тестами что-то не так, у меня проходят все.

2021-11-08 13:36 UTC, inyutin-maxim requested changes

2021-11-08 13:36 UTC, inyutin-maxim commented on VkNet/Abstractions/Core/IVkLongPollInvoke.cs
> +		(string answer, JObject answerObj) InvokeLongPoll(string server, Dictionary<string, string> parameters);
Нужно оставить обе реализации, нельзя просто так ломать обратную совместимость

2021-11-08 13:36 UTC, inyutin-maxim commented on VkNet/Abstractions/Core/IVkLongPollInvoke.cs
> +		Task<(string answer, JObject answerObj)> InvokeLongPollAsync(string server, Dictionary<string, string> parameters);
Нужно оставить обе реализации, нельзя просто так ломать обратную совместимость

2021-11-08 13:36 UTC, inyutin-maxim commented on VkNet/VkApi.cs
> +		public (string answer, JObject answerObj) InvokeLongPoll(string server, Dictionary<string, string> parameters)
Нужно оставить обе реализации, нельзя просто так ломать обратную совместимость

2021-11-08 13:36 UTC, inyutin-maxim commented on VkNet/VkApi.cs
> +		public Task<(string answer, JObject answerObj)> InvokeLongPollAsync(string server, Dictionary<string, string> parameters)
Нужно оставить обе реализации, нельзя просто так ломать обратную совместимость

2021-11-08 15:51 UTC, xeleoss commented
Сдублировал методы и добавил префикс New

2021-11-08 19:50 UTC, inyutin-maxim approved these changes

2021-11-08 19:50 UTC, inyutin-maxim commented on VkNet/Abstractions/Core/IVkLongPollInvoke.cs
> +		Task<(string answer, JObject answerObj)> InvokeLongPollNewAsync(string server, Dictionary<string, string> parameters);
Уж лучше Extended

2021-11-08 19:50 UTC, merged