photos.getMessagesUploadServer fix
vknet/vk pull request #1215
Opened 2021-11-11 00:31 UTC by Jagerente

## Список изменений
Fixed https://vk.com/dev/photos.getMessagesUploadServer.
Отправлялся неверный параметр. Вместо group_id -> peer_id, что возвращало ошибку 901.

2021-11-11 14:46 UTC, inyutin-maxim requested changes

2021-11-11 14:46 UTC, inyutin-maxim commented on VkNet/Abstractions/Category/Async/IDocsCategoryAsync.cs
> +		Task<UploadServerInfo> GetMessagesUploadServerAsync(long? group_id = null, DocMessageType type = null);
Принято именовать аргументы в camelCase нотации

2021-11-11 14:46 UTC, inyutin-maxim commented on VkNet/Abstractions/Category/Async/IPhotoCategoryAsync.cs
> +		Task<UploadServerInfo> GetMessagesUploadServerAsync(long group_id);
Принято именовать аргументы в camelCase нотации

2021-11-11 14:46 UTC, inyutin-maxim commented on VkNet/Abstractions/Category/IDocsCategory.cs
> +		UploadServerInfo GetMessagesUploadServer(long? group_id = null, DocMessageType type = null);
Принято именовать аргументы в camelCase нотации

2021-11-11 14:46 UTC, inyutin-maxim commented on VkNet/Abstractions/Category/IPhotoCategory.cs
> +		UploadServerInfo GetMessagesUploadServer(long group_id);
Принято именовать аргументы в camelCase нотации

2021-11-11 14:46 UTC, inyutin-maxim commented on VkNet/Categories/Async/DocsCategoryAsync.cs
> +			return TypeHelper.TryInvokeMethodAsync(func: () => GetMessagesUploadServer(group_id, type));
Принято именовать аргументы в camelCase нотации

2021-11-11 14:46 UTC, inyutin-maxim commented on VkNet/Categories/Async/DocsCategoryAsync.cs
> +		public Task<UploadServerInfo> GetMessagesUploadServerAsync(long? group_id = null, DocMessageType type = null)
Принято именовать аргументы в camelCase нотации

2021-11-11 14:46 UTC, inyutin-maxim commented on VkNet/Categories/Async/PhotoCategoryAsync.cs
> +		public Task<UploadServerInfo> GetMessagesUploadServerAsync(long group_id)
Принято именовать аргументы в camelCase нотации

2021-11-11 14:46 UTC, inyutin-maxim commented on VkNet/Categories/Async/PhotoCategoryAsync.cs
> +			return TypeHelper.TryInvokeMethodAsync(func: () => GetMessagesUploadServer(group_id: group_id));
Принято именовать аргументы в camelCase нотации

2021-11-11 14:46 UTC, inyutin-maxim commented on VkNet/Categories/DocsCategory.cs
> +		public UploadServerInfo GetMessagesUploadServer(long? group_id = null, DocMessageType type = null)
Принято именовать аргументы в camelCase нотации

2021-11-11 14:46 UTC, inyutin-maxim commented on VkNet/Categories/PhotoCategory.cs
> +		public UploadServerInfo GetMessagesUploadServer(long group_id)
Принято именовать аргументы в camelCase нотации

2021-11-11 19:37 UTC, merged

2021-11-28 21:18 UTC, xeleoss commented
Кажется после этого изменения у меня перестали загружаться картинки от имени сообщества.

2022-02-14 18:16 UTC, xeleoss commented
Кроме того, в photos.getMessagesUploadServer есть параметр peer_id, просто его нет в документации. Я проверил. С ним сообщество заливает фотку в беседу от имени создателя беседы, это как раз у меня и сломалось.