BotsLongPoolUpdatesProvider
vknet/vk pull request #1565
Opened 2023-07-29 22:24 UTC by xeleoss

Реализация простого лонгпула для ботов в сообществах.

2023-07-30 15:15 UTC, inyutin-maxim requested changes

2023-07-30 15:15 UTC, inyutin-maxim commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProvider.cs
> +	private void IncTs()
непонятно что делает функция, переименовать во что то понятное всем

2023-07-30 15:15 UTC, inyutin-maxim commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProvider.cs
> +	private void IncTs()
во вторых не понятно почему изменение  TS область ответственности этого класса

2023-07-30 15:15 UTC, inyutin-maxim commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProviderParams.cs
> +	/// / Функция, которая возвращает true, если работа лонгпула должна быть приостановлена
лишний слеш

2023-07-30 15:15 UTC, inyutin-maxim commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProviderParams.cs
> +	public Action<System.Exception>? OnHttpOrServerError = null;
Ну здесь смешение области ответственности, не очень удобно обрабатывать такое, лучше разделить

2023-07-30 15:15 UTC, inyutin-maxim commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProvider.cs
> +	private async Task UpdateLongPoolServerAsync(bool isInit = false, CancellationToken token = default)
зачем тут флаг `isInit` если сюда всегда `true` передается?

2023-07-30 15:15 UTC, inyutin-maxim commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProvider.cs
> +		for (var index = 0; index < updatesAndErrors.Count; index++)
Перепиши на `foreach (var (update, exception) in updatesAndErrors)`

2023-07-30 15:15 UTC, inyutin-maxim commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProviderParams.cs
> +	/// Первый параметр - response, второй - индекс события, третий - ошибка.
Лучше унести в класс, который будет красиво все описывать

2023-07-30 15:15 UTC, inyutin-maxim commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProviderParams.cs
> +	public Action<BotsLongPollHistoryResponse<JObject>, List<GroupUpdate>>? OnUpdates = null;
здесь я бы тоже наверное аргументы в класс унес

2023-07-30 15:15 UTC, inyutin-maxim commented on VkNet/Utils/BotsLongPool/BotsLongPoolHelpers.cs
> +public static class BotsLongPoolHelpers
для метода GetGroupUpdatesAndErrors результат тоже унести в класс с говорящими свойствами. Туплы погано читаются

2023-07-30 15:15 UTC, inyutin-maxim commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProvider.cs
> +		await UpdateLongPoolServerAsync(true, token);
Может быть этот вызов унести в NextLongPoolHistoryAsync если _lpResponse == null

2023-07-30 15:15 UTC, inyutin-maxim commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProvider.cs
> +			while (_params.GetPause?.Invoke() is not true)
Может быть Task.Delay с одной секундой поставить после цикла?

2023-07-30 15:58 UTC, xeleoss commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProvider.cs
> +		for (var index = 0; index < updatesAndErrors.Count; index++)
Я удалил всю функцию и сделал обёртку  GroupUpdateEvent

2023-07-30 15:58 UTC, xeleoss commented on VkNet/Utils/BotsLongPool/BotsLongPoolHelpers.cs
> +public static class BotsLongPoolHelpers
Создал класс GroupUpdateEvent

2023-07-30 16:01 UTC, xeleoss commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProvider.cs
> +		await UpdateLongPoolServerAsync(true, token);
Согласен. Готово.

2023-07-30 16:01 UTC, xeleoss commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProvider.cs
> +			while (_params.GetPause?.Invoke() is not true)
Нет, мы же не хотим чтобы лонгпул тормозил.

2023-07-30 16:04 UTC, xeleoss commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProvider.cs
> +	private async Task UpdateLongPoolServerAsync(bool isInit = false, CancellationToken token = default)
Воспользовался методом UpdateLongPoolServerAsync в другом месте. Теперь isInit бывает false.

2023-07-30 16:05 UTC, xeleoss commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProviderParams.cs
> +	public Action<System.Exception>? OnHttpOrServerError = null;
Убрал OnHttpOrServerError. Теперь эти ошибки отправляются в OnWarn, так как они незначительные и не влияют на работу.

2023-07-30 16:06 UTC, xeleoss commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProviderParams.cs
> +	/// / Функция, которая возвращает true, если работа лонгпула должна быть приостановлена
Убрал.

2023-07-30 16:11 UTC, xeleoss commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProvider.cs
> +	private void IncTs()
Написал доку к IncTs.

2023-07-30 16:18 UTC, xeleoss commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProviderParams.cs
> +	public Action<BotsLongPollHistoryResponse<JObject>, List<GroupUpdate>>? OnUpdates = null;
Создал класс BotsLongPoolOnUpdatesEvent

2023-07-30 17:04 UTC, xeleoss commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProviderParams.cs
> +	/// Первый параметр - response, второй - индекс события, третий - ошибка.
Создал класс BotsLongPoolOnUpdatesEvent

2023-07-30 18:51 UTC, inyutin-maxim requested changes

2023-07-30 18:51 UTC, inyutin-maxim commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProvider.cs
> +	public async Task RunAsync(CancellationToken token = default)
Пометить атрибутом [UsedImplicitly]

2023-07-30 18:51 UTC, inyutin-maxim commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProvider.cs
> +			while (_params.GetPause?.Invoke() is not true)
Я имею ввиду зачем каждую милисекунду опрашивать снял пользователь паузу или нет. Это сильно жрет ресурсы

2023-08-01 20:57 UTC, inyutin-maxim approved these changes

2023-08-01 20:57 UTC, inyutin-maxim commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProvider.cs
> +	private void IncTs()
Почему бы в классе `LongPollServerResponse` не сделать метод который бы увеличивал TS. Но этот вариант тоже не самый лучший, скорее даже надо ввести поле отвечающее за TS, и использовать его состояние

2023-08-01 20:57 UTC, inyutin-maxim commented on VkNet/Utils/BotsLongPool/BotsLongPoolUpdatesProvider.cs
> +		while (true)
Все таки хотя бы токеном надо дать возможность прервать выполнение

2023-08-01 20:58 UTC, merged