#1222 Add support for method podcast.searchPodcast
vknet/vk pull request #1572
Opened 2023-08-11 16:24 UTC by Rahovski

## List of changes
- added support for method podcast.searchPodcast
- old podcast methods marked as *Deprecated* ( **Warning**: vk support team said, that api for podcast is offline )
- added new model *VkNet/Model/Results/Podcasts/PodcastSearchInfo.cs* and rebuilded model *VkNet/Model/Results/Podcasts/PodcastsSearchResult.cs* for support new format of answer from api method
- rebuilded test sources and test cases for 'podcast.searchPodcast' method

[Source for podcast.searchPodcast](https://dev.vk.com/ru/method/podcasts.searchPodcast)

## Additional info about podcast methods
![изображение](https://github.com/vknet/vk/assets/9554636/89360618-30ea-4d91-99f7-abdf50056d29)

2023-08-11 19:21 UTC, Panuchi requested changes

2023-08-11 19:21 UTC, Panuchi commented on VkNet/Abstractions/Category/Async/IPodcastsCategoryAsync.cs
>  	/// Страница документации ВКонтакте https://vk.com/dev/podcasts.search
Здесь тоже изменить название метода

2023-08-11 19:31 UTC, Rahovski commented on VkNet/Abstractions/Category/Async/IPodcastsCategoryAsync.cs
>  	/// Страница документации ВКонтакте https://vk.com/dev/podcasts.search
@Panuchi Done. Request Review

2023-08-11 19:35 UTC, Panuchi requested changes

2023-08-11 19:35 UTC, Panuchi commented on VkNet.Tests/TestData/Categories/Podcasts/SearchPodcast.json
Нужно сократить до минимального размера, убрать дубликаты и похожие данные

2023-08-11 19:46 UTC, Rahovski commented on VkNet.Tests/TestData/Categories/Podcasts/SearchPodcast.json
@Panuchi Это боевой тест с реальной выдачи с запроса на апи. 
Устроит, если ответ будет содержать коллекцию из 10-12 элементов?

2023-08-12 08:02 UTC, Rahovski commented on VkNet.Tests/TestData/Categories/Podcasts/SearchPodcast.json
Thread closed by [commit](https://github.com/vknet/vk/pull/1572/commits/9ba2dd02c4409f9e17f7ab753ef9ce6f91accb9e)

2023-08-12 08:33 UTC, ghost commented on VkNet.Tests/TestData/Categories/Podcasts/SearchPodcast.json
> @Panuchi Это боевой тест с реальной выдачи с запроса на апи. Устроит, если ответ будет содержать коллекцию из 10-12 элементов?

У всех элементов одинаковая структура, можно сократить до 1-2.

2023-08-13 19:55 UTC, merged