Add fields for method "market.get"
vknet/vk pull request #1580
Opened 2023-08-21 17:55 UTC by Rahovski

## List of changes
- added support for new fields of method *[market.get](https://dev.vk.com/ru/method/market.get)* - date_from, date_to, need_variants, with_disabled
- added model *MarketGetParams* for wrap arguments for method *market.get*
- added unit test and test data for thid method

[Source of args](https://dev.vk.com/ru/method/market.get)

2023-08-21 18:03 UTC, Rahovski commented
@Panuchi @inyutin-maxim Request restart github actions, cause it fall on stage to send telegram notification 
[Link](https://github.com/vknet/vk/actions/runs/5929776874/job/16078145871?pr=1580)
![изображение](https://github.com/vknet/vk/assets/9554636/359c3e4c-a054-4224-b8bf-3b7bc7893e7d)

2023-08-21 19:08 UTC, inyutin-maxim approved these changes

2023-08-21 19:10 UTC, inyutin-maxim requested changes

2023-08-21 19:10 UTC, inyutin-maxim commented on VkNet/Abstractions/Category/Async/IMarketsCategoryAsync.cs
> -	Task<VkCollection<Market>> GetAsync(long ownerId,
Restore and mark as obsolete with comment for use new method, with compilation error

2023-08-27 21:30 UTC, Rahovski commented on VkNet/Abstractions/Category/Async/IMarketsCategoryAsync.cs
> -	Task<VkCollection<Market>> GetAsync(long ownerId,
@inyutin-maxim 
Done, but:
* Marked method is obsolete in [MarketCategory.cs](https://github.com/vknet/vk/blob/develop/VkNet/Categories/MarketsCategory.cs), cause if i mark *getAsync* method in interface - IDE require mark all *get market* methods

2023-08-28 13:19 UTC, inyutin-maxim commented
@Rahovski Please resolve conflicts

2023-08-28 13:20 UTC, inyutin-maxim approved these changes

2023-08-28 13:37 UTC, inyutin-maxim approved these changes

2023-08-28 13:38 UTC, merged