#710 Реализовал не блокирующий потоки RateLimiter для ограничения частоты запросов
vknet/vk pull request #736
Opened 2018-11-12 20:51 UTC by itsokto

## Список изменений
- Реализовал не блокирующий потоки `RateLimiter` для ограничения частоты запросов.

2018-11-12 21:46 UTC, inyutin-maxim requested changes

2018-11-12 21:46 UTC, inyutin-maxim commented on VkNet/VkNet.csproj
> +		<PackageReference Include="Microsoft.Bcl.Build" Version="1.0.21" />
Верни взад старую версию

2018-11-12 21:46 UTC, inyutin-maxim commented on VkNet/Utils/Async/AsyncSemaphoreSlim.cs
> +		if (initialCount < 0) throw new ArgumentOutOfRangeException("initialCount");
Примени к измененному коду **Resharper CodeStyle** объявленный в **.editorconfig** файле. Для этого Нужно выполнить в **Resharper** или **Rider** команду **Code Cleanup..**.

2018-11-12 21:46 UTC, inyutin-maxim commented on VkNet/Utils/Async/AsyncSemaphoreSlim.cs
> +		if (initialCount < 0) throw new ArgumentOutOfRangeException("initialCount");
uint решил бы эту проверку)

2018-11-12 21:46 UTC, inyutin-maxim commented on VkNet/Utils/CountByIntervalAwaitableConstraint.cs
> +				await Task.Delay(timetoWait, cancellationToken);
timeToWait

2018-11-12 21:46 UTC, inyutin-maxim commented on VkNet/Utils/CountByIntervalAwaitableConstraint.cs
> +			while (element != null && element.Value > target)
element?.Value > target

2018-11-12 21:46 UTC, inyutin-maxim commented on VkNet/Utils/CountByIntervalAwaitableConstraint.cs
> +			if (count <= 0)
uint бы здесь подошел, но правда проверку на 0 не уберет

2018-11-12 21:46 UTC, inyutin-maxim commented on VkNet/Utils/CountByIntervalAwaitableConstraint.cs
> +			await _semaphore.WaitAsync(cancellationToken);
в асинхронном коде можно чуть чаще бросать эксепшн CancellationToken'a

2018-11-12 21:46 UTC, inyutin-maxim commented on VkNet/Utils/CountByIntervalAwaitableConstraint.cs
> +		private readonly SemaphoreSlim _semaphore = new SemaphoreSlim(1, 1);
Я бы обернул в декоратор, выделил интерфейс и через DI бы заиспользовал

2018-11-12 21:46 UTC, inyutin-maxim commented on VkNet/Utils/LimitedSizeStack.cs
> +			if (Count > _maxSize)
Примени к измененному коду **Resharper CodeStyle** объявленный в **.editorconfig** файле. Для этого Нужно выполнить в **Resharper** или **Rider** команду **Code Cleanup..**.

2018-11-12 21:46 UTC, inyutin-maxim commented on VkNet/Utils/CountByIntervalAwaitableConstraint.cs
> +			if (timeSpan.TotalMilliseconds <= 0)
Примени к измененному коду **Resharper CodeStyle** объявленный в **.editorconfig** файле. Для этого Нужно выполнить в **Resharper** или **Rider** команду **Code Cleanup..**.

2018-11-12 21:46 UTC, inyutin-maxim commented on VkNet/Utils/Async/AsyncSemaphoreSlim.cs
> +			else
Примени к измененному коду **Resharper CodeStyle** объявленный в **.editorconfig** файле. Для этого Нужно выполнить в **Resharper** или **Rider** команду **Code Cleanup..**.

2018-11-12 22:08 UTC, inyutin-maxim requested changes

2018-11-12 22:08 UTC, inyutin-maxim commented on VkNet/VkApi.cs
> +			if (_expireTimer == null)
Примени к измененному коду **Resharper CodeStyle** объявленный в **.editorconfig** файле. Для этого Нужно выполнить в **Resharper** или **Rider** команду **Code Cleanup..**.

2018-11-13 00:08 UTC, itsokto commented on VkNet/Utils/CountByIntervalAwaitableConstraint.cs
> +			await _semaphore.WaitAsync(cancellationToken);
`cancellationToken` передаётся в `WaitAsync` где и будет вызван, если нужно.

2018-11-13 11:49 UTC, inyutin-maxim requested changes

2018-11-13 11:49 UTC, inyutin-maxim commented on VkNet/Utils/CountByIntervalAwaitableConstraint.cs
> +			OnEnded(now);
а здесь не **new DisposableAction(OnEnded)**? странно))

2018-11-13 13:59 UTC, itsokto commented on VkNet/Utils/CountByIntervalAwaitableConstraint.cs
> +			OnEnded(now);
Выпилил это, т.к. не знаю для чего автор так сделал.

2018-11-13 20:52 UTC, inyutin-maxim approved these changes

2018-11-13 20:52 UTC, merged